name: check

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: goreleaser/goreleaser-action@v6.2.1
        with:
          distribution: goreleaser
          install-only: true
      - name: check
        run: |
          goreleaser check
